# Generated by Django 5.0.1 on 2024-06-08 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='category_name',
            new_name='category_obj',
        ),
    ]
